pgadapter:
  image: postgres:10.5
  container_name: pgadapter
  ports:
    - 5432:5432
  volumes:
    - ./init:/docker-entrypoint-initdb.d
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRESS_INITDB_ARGS: "--encoding=UTF-8"
  hostname: pgadapter
  restart: always
  user: root
